# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'games_details_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gamedetails_mainwindow(object):
    def setupUi(self, gamedetails_mainwindow):
        gamedetails_mainwindow.setObjectName("gamedetails_mainwindow")
        gamedetails_mainwindow.resize(962, 426)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/default_images/icons/gamepass logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        gamedetails_mainwindow.setWindowIcon(icon)
        gamedetails_mainwindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(gamedetails_mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logoicon = QtWidgets.QPushButton(self.centralwidget)
        self.logoicon.setGeometry(QtCore.QRect(60, 10, 61, 51))
        self.logoicon.setStyleSheet("border-image: url(:/default_images/icons/gamepass logo.png);")
        self.logoicon.setText("")
        self.logoicon.setObjectName("logoicon")
        self.LogoFont = QtWidgets.QLabel(self.centralwidget)
        self.LogoFont.setGeometry(QtCore.QRect(140, 20, 201, 31))
        self.LogoFont.setStyleSheet("font: 17pt \"Bahnschrift SemiLight Condensed\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.LogoFont.setObjectName("LogoFont")
        self.upperusericon = QtWidgets.QLabel(self.centralwidget)
        self.upperusericon.setGeometry(QtCore.QRect(760, 5, 28, 28))
        self.upperusericon.setStyleSheet("\n"
"border-image: url(:/dashboard_icons/Downloads/user.png);")
        self.upperusericon.setText("")
        self.upperusericon.setObjectName("upperusericon")
        self.placeholder_username = QtWidgets.QLabel(self.centralwidget)
        self.placeholder_username.setGeometry(QtCore.QRect(800, 20, 101, 21))
        self.placeholder_username.setStyleSheet("border-image: url(:/game_details_page/Downloads/bggggg.png);\n"
"font: 10pt \"Bahnschrift SemiLight Condensed\";\n"
"border-radius: 10px;\n"
"\n"
"")
        self.placeholder_username.setAlignment(QtCore.Qt.AlignCenter)
        self.placeholder_username.setObjectName("placeholder_username")
        self.gray_gamedetails_container = QtWidgets.QWidget(self.centralwidget)
        self.gray_gamedetails_container.setGeometry(QtCore.QRect(570, 90, 291, 291))
        self.gray_gamedetails_container.setStyleSheet("background-color: rgb(56, 56, 56,160);\n"
"border-radius: 20px;")
        self.gray_gamedetails_container.setObjectName("gray_gamedetails_container")
        self.downloadnow_button = QtWidgets.QPushButton(self.gray_gamedetails_container)
        self.downloadnow_button.setGeometry(QtCore.QRect(100, 140, 91, 31))
        self.downloadnow_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.downloadnow_button.setStyleSheet("font: 10pt \"Bahnschrift SemiLight Condensed\";\n"
"background-color: rgb(253, 183, 69);\n"
"border-radius: 15px;")
        self.downloadnow_button.setCheckable(False)
        self.downloadnow_button.setFlat(False)
        self.downloadnow_button.setObjectName("downloadnow_button")
        self.releasedate_gamedetails = QtWidgets.QLabel(self.gray_gamedetails_container)
        self.releasedate_gamedetails.setGeometry(QtCore.QRect(20, 190, 81, 16))
        self.releasedate_gamedetails.setStyleSheet("color: rgb(199, 199, 199);\n"
"font: 10pt \"Bahnschrift SemiLight Condensed\";\n"
"background:transparent ;\n"
"border: none;\n"
"")
        self.releasedate_gamedetails.setObjectName("releasedate_gamedetails")
        self.developer_gamedetails = QtWidgets.QLabel(self.gray_gamedetails_container)
        self.developer_gamedetails.setGeometry(QtCore.QRect(20, 220, 81, 16))
        self.developer_gamedetails.setStyleSheet("color: rgb(199, 199, 199);\n"
"font: 10pt \"Bahnschrift SemiLight Condensed\";\n"
"background:transparent ;\n"
"border: none;\n"
"")
        self.developer_gamedetails.setObjectName("developer_gamedetails")
        self.publisher_gamedetails = QtWidgets.QLabel(self.gray_gamedetails_container)
        self.publisher_gamedetails.setGeometry(QtCore.QRect(20, 240, 81, 16))
        self.publisher_gamedetails.setStyleSheet("color: rgb(199, 199, 199);\n"
"font: 10pt \"Bahnschrift SemiLight Condensed\";\n"
"background:transparent ;\n"
"border: none;\n"
"")
        self.publisher_gamedetails.setObjectName("publisher_gamedetails")
        self.placeholder_releasedate = QtWidgets.QLabel(self.gray_gamedetails_container)
        self.placeholder_releasedate.setGeometry(QtCore.QRect(120, 190, 81, 16))
        self.placeholder_releasedate.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Bahnschrift SemiLight Condensed\";\n"
"background:transparent ;\n"
"border: none;\n"
"")
        self.placeholder_releasedate.setObjectName("placeholder_releasedate")
        self.placeholder_developer = QtWidgets.QLabel(self.gray_gamedetails_container)
        self.placeholder_developer.setGeometry(QtCore.QRect(120, 220, 81, 16))
        self.placeholder_developer.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Bahnschrift SemiLight Condensed\";\n"
"background:transparent ;\n"
"border: none;\n"
"")
        self.placeholder_developer.setObjectName("placeholder_developer")
        self.placeholder_publisher = QtWidgets.QLabel(self.gray_gamedetails_container)
        self.placeholder_publisher.setGeometry(QtCore.QRect(120, 240, 191, 16))
        self.placeholder_publisher.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Bahnschrift SemiLight Condensed\";\n"
"background:transparent ;\n"
"border: none;\n"
"")
        self.placeholder_publisher.setObjectName("placeholder_publisher")
        self.placeholder_gameminipicture = QtWidgets.QWidget(self.gray_gamedetails_container)
        self.placeholder_gameminipicture.setGeometry(QtCore.QRect(80, 20, 131, 81))
        self.placeholder_gameminipicture.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px")
        self.placeholder_gameminipicture.setObjectName("placeholder_gameminipicture")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(90, 470, 31, 31))
        self.pushButton_7.setStyleSheet("border-image: url(:/game_details_page/Downloads/back (2).png);\n"
"background:transparent ;\n"
"border: none;")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(840, 470, 31, 31))
        self.pushButton_8.setStyleSheet("border-image: url(:/game_details_page/Downloads/next (2).png);\n"
"background:transparent ;\n"
"border: none;")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(140, 450, 111, 61))
        self.label_11.setStyleSheet("border-image: url(:/game_details_page/Downloads/image (2).png);\n"
"border-radius: 10px;")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(290, 450, 111, 61))
        self.label_12.setStyleSheet("border-image: url(:/game_details_page/Downloads/image (5).png);\n"
"border-radius: 10px;")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(430, 450, 111, 61))
        self.label_13.setStyleSheet("border-image: url(:/game_details_page/Downloads/image (4).png);\n"
"border-radius: 10px;")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(570, 450, 111, 61))
        self.label_14.setStyleSheet("border-image: url(:/game_details_page/Downloads/image (1).png);\n"
"border-radius: 10px;")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(710, 450, 111, 61))
        self.label_15.setStyleSheet("border-image: url(:/game_details_page/Downloads/image (3).png);\n"
"border-radius: 10px;")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.placeholder_game = QtWidgets.QWidget(self.centralwidget)
        self.placeholder_game.setGeometry(QtCore.QRect(110, 90, 391, 291))
        self.placeholder_game.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px")
        self.placeholder_game.setObjectName("placeholder_game")
        gamedetails_mainwindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(gamedetails_mainwindow)
        QtCore.QMetaObject.connectSlotsByName(gamedetails_mainwindow)

    def retranslateUi(self, gamedetails_mainwindow):
        _translate = QtCore.QCoreApplication.translate
        gamedetails_mainwindow.setWindowTitle(_translate("gamedetails_mainwindow", "Game Details"))
        self.LogoFont.setText(_translate("gamedetails_mainwindow", "DonnelJan Game Pass"))
        self.placeholder_username.setText(_translate("gamedetails_mainwindow", "placeholder_username"))
        self.downloadnow_button.setText(_translate("gamedetails_mainwindow", "DOWNLOAD NOW"))
        self.releasedate_gamedetails.setText(_translate("gamedetails_mainwindow", "RELEASE DATE:"))
        self.developer_gamedetails.setText(_translate("gamedetails_mainwindow", "DEVELOPER:"))
        self.publisher_gamedetails.setText(_translate("gamedetails_mainwindow", "PUBLISHER:"))
        self.placeholder_releasedate.setText(_translate("gamedetails_mainwindow", "N/A"))
        self.placeholder_developer.setText(_translate("gamedetails_mainwindow", "N/A"))
        self.placeholder_publisher.setText(_translate("gamedetails_mainwindow", "N/A"))

from resources import system_images


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gamedetails_mainwindow = QtWidgets.QMainWindow()
    ui = Ui_gamedetails_mainwindow()
    ui.setupUi(gamedetails_mainwindow)
    gamedetails_mainwindow.show()
    sys.exit(app.exec_())
