import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit, QMessageBox

from utils.navigation import navigation

class Ui_loginregister_mainwindow(object):
        def setupUi(self, loginregister_mainwindow):
                loginregister_mainwindow.setObjectName("loginregister_mainwindow")
                loginregister_mainwindow.resize(986, 600)
                loginregister_mainwindow.setMinimumSize(QtCore.QSize(986, 600))
                loginregister_mainwindow.setMaximumSize(QtCore.QSize(986, 600))
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap(":/default_images/icons/gamepass logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                loginregister_mainwindow.setWindowIcon(icon)
                loginregister_mainwindow.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.centralwidget = QtWidgets.QWidget(loginregister_mainwindow)
                self.centralwidget.setObjectName("centralwidget")
                self.loginregister_widget = QtWidgets.QStackedWidget(self.centralwidget)
                self.loginregister_widget.setGeometry(QtCore.QRect(70, 10, 871, 571))
                self.loginregister_widget.setObjectName("loginregister_widget")
                self.login_page = QtWidgets.QWidget()
                self.login_page.setObjectName("login_page")
                self.layoutWidget = QtWidgets.QWidget(self.login_page)
                self.layoutWidget.setGeometry(QtCore.QRect(210, 30, 423, 509))
                self.layoutWidget.setObjectName("layoutWidget")
                self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
                self.verticalLayout.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout.setObjectName("verticalLayout")
                self.system_title = QtWidgets.QLabel(self.layoutWidget)
                self.system_title.setMinimumSize(QtCore.QSize(401, 91))
                self.system_title.setMaximumSize(QtCore.QSize(401, 91))
                self.system_title.setText("")
                self.system_title.setPixmap(QtGui.QPixmap(":/default_images/images/system__title.png"))
                self.system_title.setScaledContents(True)
                self.system_title.setObjectName("system_title")
                self.verticalLayout.addWidget(self.system_title)
                spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
                self.verticalLayout.addItem(spacerItem)
                self.yellow_container_login = QtWidgets.QWidget(self.layoutWidget)
                self.yellow_container_login.setMinimumSize(QtCore.QSize(421, 391))
                self.yellow_container_login.setMaximumSize(QtCore.QSize(421, 391))
                self.yellow_container_login.setStyleSheet("background-color: rgb(252, 183, 68);\n"
        "border-radius: 20px;")
                self.yellow_container_login.setObjectName("yellow_container_login")
                self.logintitle_login = QtWidgets.QLabel(self.yellow_container_login)
                self.logintitle_login.setEnabled(True)
                self.logintitle_login.setGeometry(QtCore.QRect(120, 10, 181, 61))
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
                sizePolicy.setHorizontalStretch(181)
                sizePolicy.setVerticalStretch(61)
                sizePolicy.setHeightForWidth(self.logintitle_login.sizePolicy().hasHeightForWidth())
                self.logintitle_login.setSizePolicy(sizePolicy)
                self.logintitle_login.setMinimumSize(QtCore.QSize(181, 61))
                font = QtGui.QFont()
                font.setFamily("Bahnschrift SemiLight SemiConde")
                font.setPointSize(18)
                self.logintitle_login.setFont(font)
                self.logintitle_login.setAlignment(QtCore.Qt.AlignCenter)
                self.logintitle_login.setObjectName("logintitle_login")
                self.layoutWidget1 = QtWidgets.QWidget(self.yellow_container_login)
                self.layoutWidget1.setGeometry(QtCore.QRect(40, 330, 351, 43))
                self.layoutWidget1.setObjectName("layoutWidget1")
                self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
                self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout.setObjectName("horizontalLayout")
                self.back_button_login = QtWidgets.QPushButton(self.layoutWidget1)
                self.back_button_login.setMinimumSize(QtCore.QSize(111, 41))
                self.back_button_login.setMaximumSize(QtCore.QSize(111, 41))
                font = QtGui.QFont()
                font.setFamily("Bahnschrift SemiBold SemiConden")
                font.setPointSize(11)
                font.setBold(True)
                font.setWeight(75)
                self.back_button_login.setFont(font)
                self.back_button_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.back_button_login.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.back_button_login.setObjectName("back_button_login")
                self.horizontalLayout.addWidget(self.back_button_login)
                self.enter_button_login = QtWidgets.QPushButton(self.layoutWidget1)
                self.enter_button_login.setMinimumSize(QtCore.QSize(101, 41))
                self.enter_button_login.setMaximumSize(QtCore.QSize(101, 41))
                font = QtGui.QFont()
                font.setFamily("Bahnschrift SemiBold SemiConden")
                font.setPointSize(11)
                font.setBold(True)
                font.setWeight(75)
                self.enter_button_login.setFont(font)
                self.enter_button_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.enter_button_login.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.enter_button_login.setObjectName("enter_button_login")
                self.horizontalLayout.addWidget(self.enter_button_login)
                self.register_button_login = QtWidgets.QPushButton(self.layoutWidget1)
                self.register_button_login.setMinimumSize(QtCore.QSize(91, 41))
                self.register_button_login.setMaximumSize(QtCore.QSize(91, 41))
                font = QtGui.QFont()
                font.setFamily("Bahnschrift SemiLight SemiConde")
                font.setPointSize(11)
                self.register_button_login.setFont(font)
                self.register_button_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.register_button_login.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.register_button_login.setObjectName("register_button_login")
                self.horizontalLayout.addWidget(self.register_button_login)
                self.layoutWidget2 = QtWidgets.QWidget(self.yellow_container_login)
                self.layoutWidget2.setGeometry(QtCore.QRect(40, 130, 340, 33))
                self.layoutWidget2.setObjectName("layoutWidget2")
                self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
                self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_2.setObjectName("horizontalLayout_2")
                self.usernametitle_login = QtWidgets.QLabel(self.layoutWidget2)
                self.usernametitle_login.setMinimumSize(QtCore.QSize(91, 21))
                self.usernametitle_login.setMaximumSize(QtCore.QSize(91, 21))
                font = QtGui.QFont()
                font.setFamily("Bahnschrift SemiBold Condensed")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.usernametitle_login.setFont(font)
                self.usernametitle_login.setAlignment(QtCore.Qt.AlignCenter)
                self.usernametitle_login.setObjectName("usernametitle_login")
                self.horizontalLayout_2.addWidget(self.usernametitle_login)
                self.username_lineedit_login = QtWidgets.QLineEdit(self.layoutWidget2)
                self.username_lineedit_login.setMinimumSize(QtCore.QSize(241, 31))
                self.username_lineedit_login.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.username_lineedit_login.setObjectName("username_lineedit_login")
                self.horizontalLayout_2.addWidget(self.username_lineedit_login)
                self.layoutWidget3 = QtWidgets.QWidget(self.yellow_container_login)
                self.layoutWidget3.setGeometry(QtCore.QRect(40, 220, 340, 33))
                self.layoutWidget3.setObjectName("layoutWidget3")
                self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget3)
                self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_3.setObjectName("horizontalLayout_3")
                self.passwordtitle_login = QtWidgets.QLabel(self.layoutWidget3)
                self.passwordtitle_login.setMinimumSize(QtCore.QSize(91, 21))
                self.passwordtitle_login.setMaximumSize(QtCore.QSize(91, 21))
                font = QtGui.QFont()
                font.setFamily("Bahnschrift SemiBold Condensed")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.passwordtitle_login.setFont(font)
                self.passwordtitle_login.setAlignment(QtCore.Qt.AlignCenter)
                self.passwordtitle_login.setObjectName("passwordtitle_login")
                self.horizontalLayout_3.addWidget(self.passwordtitle_login)
                self.password_lineedit_login = QtWidgets.QLineEdit(self.layoutWidget3)
                self.password_lineedit_login.setMinimumSize(QtCore.QSize(241, 31))
                self.password_lineedit_login.setMaximumSize(QtCore.QSize(241, 31))
                self.password_lineedit_login.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
                self.password_lineedit_login.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.password_lineedit_login.setObjectName("password_lineedit_login")
                self.password_lineedit_login.setEchoMode(QtWidgets.QLineEdit.Password)
                self.horizontalLayout_3.addWidget(self.password_lineedit_login)
                self.showpassword_button_login = QtWidgets.QPushButton(self.yellow_container_login)
                self.showpassword_button_login.setGeometry(QtCore.QRect(280, 260, 101, 23))
                self.showpassword_button_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.showpassword_button_login.setObjectName("showpassword_button_login")
                self.verticalLayout.addWidget(self.yellow_container_login)
                self.loginregister_widget.addWidget(self.login_page)
                self.register_page = QtWidgets.QWidget()
                self.register_page.setObjectName("register_page")
                self.layoutWidget_2 = QtWidgets.QWidget(self.register_page)
                self.layoutWidget_2.setGeometry(QtCore.QRect(210, 30, 423, 509))
                self.layoutWidget_2.setObjectName("layoutWidget_2")
                self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
                self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout_2.setObjectName("verticalLayout_2")
                self.system_title_2 = QtWidgets.QLabel(self.layoutWidget_2)
                self.system_title_2.setMinimumSize(QtCore.QSize(401, 91))
                self.system_title_2.setMaximumSize(QtCore.QSize(401, 91))
                self.system_title_2.setText("")
                self.system_title_2.setPixmap(QtGui.QPixmap(":/default_images/images/system__title.png"))
                self.system_title_2.setScaledContents(True)
                self.system_title_2.setObjectName("system_title_2")
                self.verticalLayout_2.addWidget(self.system_title_2)
                spacerItem1 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
                self.verticalLayout_2.addItem(spacerItem1)
                self.yellow_container_register = QtWidgets.QWidget(self.layoutWidget_2)
                self.yellow_container_register.setMinimumSize(QtCore.QSize(421, 391))
                self.yellow_container_register.setMaximumSize(QtCore.QSize(421, 391))
                self.yellow_container_register.setStyleSheet("background-color: rgb(252, 183, 68);\n"
        "border-radius: 20px;")
                self.yellow_container_register.setObjectName("yellow_container_register")
                self.regitertitle_register = QtWidgets.QLabel(self.yellow_container_register)
                self.regitertitle_register.setGeometry(QtCore.QRect(120, 10, 181, 61))
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
                sizePolicy.setHorizontalStretch(181)
                sizePolicy.setVerticalStretch(61)
                sizePolicy.setHeightForWidth(self.regitertitle_register.sizePolicy().hasHeightForWidth())
                self.regitertitle_register.setSizePolicy(sizePolicy)
                self.regitertitle_register.setMinimumSize(QtCore.QSize(181, 61))
                font = QtGui.QFont()
                font.setFamily("Bahnschrift SemiLight SemiConde")
                font.setPointSize(18)
                self.regitertitle_register.setFont(font)
                self.regitertitle_register.setAlignment(QtCore.Qt.AlignCenter)
                self.regitertitle_register.setObjectName("regitertitle_register")
                self.layoutWidget_3 = QtWidgets.QWidget(self.yellow_container_register)
                self.layoutWidget_3.setGeometry(QtCore.QRect(40, 320, 351, 43))
                self.layoutWidget_3.setObjectName("layoutWidget_3")
                self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
                self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_4.setObjectName("horizontalLayout_4")
                self.back_button_register = QtWidgets.QPushButton(self.layoutWidget_3)
                self.back_button_register.setMinimumSize(QtCore.QSize(111, 41))
                self.back_button_register.setMaximumSize(QtCore.QSize(111, 41))
                font = QtGui.QFont()
                font.setFamily("Bahnschrift SemiBold SemiConden")
                font.setPointSize(11)
                font.setBold(True)
                font.setWeight(75)
                self.back_button_register.setFont(font)
                self.back_button_register.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.back_button_register.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.back_button_register.setObjectName("back_button_register")
                self.horizontalLayout_4.addWidget(self.back_button_register)
                self.enter_button_register = QtWidgets.QPushButton(self.layoutWidget_3)
                self.enter_button_register.setMinimumSize(QtCore.QSize(101, 41))
                self.enter_button_register.setMaximumSize(QtCore.QSize(101, 41))
                font = QtGui.QFont()
                font.setFamily("Bahnschrift SemiBold SemiConden")
                font.setPointSize(11)
                font.setBold(True)
                font.setWeight(75)
                self.enter_button_register.setFont(font)
                self.enter_button_register.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.enter_button_register.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.enter_button_register.setObjectName("enter_button_register")
                self.horizontalLayout_4.addWidget(self.enter_button_register)
                self.layoutWidget_4 = QtWidgets.QWidget(self.yellow_container_register)
                self.layoutWidget_4.setGeometry(QtCore.QRect(40, 180, 340, 33))
                self.layoutWidget_4.setObjectName("layoutWidget_4")
                self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
                self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_5.setObjectName("horizontalLayout_5")
                self.usernametitle_register = QtWidgets.QLabel(self.layoutWidget_4)
                self.usernametitle_register.setMinimumSize(QtCore.QSize(91, 21))
                self.usernametitle_register.setMaximumSize(QtCore.QSize(91, 21))
                font = QtGui.QFont()
                font.setFamily("Bahnschrift SemiBold Condensed")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.usernametitle_register.setFont(font)
                self.usernametitle_register.setAlignment(QtCore.Qt.AlignCenter)
                self.usernametitle_register.setObjectName("usernametitle_register")
                self.horizontalLayout_5.addWidget(self.usernametitle_register)
                self.username_lineedit_register = QtWidgets.QLineEdit(self.layoutWidget_4)
                self.username_lineedit_register.setMinimumSize(QtCore.QSize(241, 31))
                self.username_lineedit_register.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.username_lineedit_register.setObjectName("username_lineedit_register")
                self.horizontalLayout_5.addWidget(self.username_lineedit_register)
                self.layoutWidget_5 = QtWidgets.QWidget(self.yellow_container_register)
                self.layoutWidget_5.setGeometry(QtCore.QRect(40, 220, 340, 33))
                self.layoutWidget_5.setObjectName("layoutWidget_5")
                self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
                self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_6.setObjectName("horizontalLayout_6")
                self.passwordtitle_register = QtWidgets.QLabel(self.layoutWidget_5)
                self.passwordtitle_register.setMinimumSize(QtCore.QSize(91, 21))
                self.passwordtitle_register.setMaximumSize(QtCore.QSize(91, 21))
                font = QtGui.QFont()
                font.setFamily("Bahnschrift SemiBold Condensed")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.passwordtitle_register.setFont(font)
                self.passwordtitle_register.setAlignment(QtCore.Qt.AlignCenter)
                self.passwordtitle_register.setObjectName("passwordtitle_register")
                self.horizontalLayout_6.addWidget(self.passwordtitle_register)
                self.password_lineedit_register = QtWidgets.QLineEdit(self.layoutWidget_5)
                self.password_lineedit_register.setMinimumSize(QtCore.QSize(241, 31))
                self.password_lineedit_register.setMaximumSize(QtCore.QSize(241, 31))
                self.password_lineedit_register.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.password_lineedit_register.setObjectName("password_lineedit_register")
                self.horizontalLayout_6.addWidget(self.password_lineedit_register)
                self.layoutWidget_6 = QtWidgets.QWidget(self.yellow_container_register)
                self.layoutWidget_6.setGeometry(QtCore.QRect(40, 60, 340, 33))
                self.layoutWidget_6.setObjectName("layoutWidget_6")
                self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
                self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_7.setObjectName("horizontalLayout_7")
                self.firstnametitle_register = QtWidgets.QLabel(self.layoutWidget_6)
                self.firstnametitle_register.setMinimumSize(QtCore.QSize(91, 21))
                self.firstnametitle_register.setMaximumSize(QtCore.QSize(91, 21))
                font = QtGui.QFont()
                font.setFamily("Bahnschrift SemiBold Condensed")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.firstnametitle_register.setFont(font)
                self.firstnametitle_register.setAlignment(QtCore.Qt.AlignCenter)
                self.firstnametitle_register.setObjectName("firstnametitle_register")
                self.horizontalLayout_7.addWidget(self.firstnametitle_register)
                self.firstname_lineedit_register = QtWidgets.QLineEdit(self.layoutWidget_6)
                self.firstname_lineedit_register.setMinimumSize(QtCore.QSize(241, 31))
                self.firstname_lineedit_register.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.firstname_lineedit_register.setObjectName("firstname_lineedit_register")
                self.horizontalLayout_7.addWidget(self.firstname_lineedit_register)
                self.layoutWidget_7 = QtWidgets.QWidget(self.yellow_container_register)
                self.layoutWidget_7.setGeometry(QtCore.QRect(40, 100, 340, 33))
                self.layoutWidget_7.setObjectName("layoutWidget_7")
                self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
                self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_8.setObjectName("horizontalLayout_8")
                self.lastnametitle_register = QtWidgets.QLabel(self.layoutWidget_7)
                self.lastnametitle_register.setMinimumSize(QtCore.QSize(91, 21))
                self.lastnametitle_register.setMaximumSize(QtCore.QSize(91, 21))
                font = QtGui.QFont()
                font.setFamily("Bahnschrift SemiBold Condensed")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.lastnametitle_register.setFont(font)
                self.lastnametitle_register.setAlignment(QtCore.Qt.AlignCenter)
                self.lastnametitle_register.setObjectName("lastnametitle_register")
                self.horizontalLayout_8.addWidget(self.lastnametitle_register)
                self.lastname_lineedit_register = QtWidgets.QLineEdit(self.layoutWidget_7)
                self.lastname_lineedit_register.setMinimumSize(QtCore.QSize(241, 31))
                self.lastname_lineedit_register.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.lastname_lineedit_register.setObjectName("lastname_lineedit_register")
                self.horizontalLayout_8.addWidget(self.lastname_lineedit_register)
                self.layoutWidget_8 = QtWidgets.QWidget(self.yellow_container_register)
                self.layoutWidget_8.setGeometry(QtCore.QRect(40, 260, 340, 33))
                self.layoutWidget_8.setObjectName("layoutWidget_8")
                self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
                self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_9.setObjectName("horizontalLayout_9")
                self.confirmpasswordtitle_register = QtWidgets.QLabel(self.layoutWidget_8)
                self.confirmpasswordtitle_register.setMinimumSize(QtCore.QSize(91, 21))
                self.confirmpasswordtitle_register.setMaximumSize(QtCore.QSize(91, 21))
                font = QtGui.QFont()
                font.setFamily("Bahnschrift SemiBold Condensed")
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.confirmpasswordtitle_register.setFont(font)
                self.confirmpasswordtitle_register.setObjectName("confirmpasswordtitle_register")
                self.horizontalLayout_9.addWidget(self.confirmpasswordtitle_register)
                self.confirmpassword_lineedit_register = QtWidgets.QLineEdit(self.layoutWidget_8)
                self.confirmpassword_lineedit_register.setMinimumSize(QtCore.QSize(241, 31))
                self.confirmpassword_lineedit_register.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.confirmpassword_lineedit_register.setObjectName("confirmpassword_lineedit_register")
                self.horizontalLayout_9.addWidget(self.confirmpassword_lineedit_register)
                self.layoutWidget_9 = QtWidgets.QWidget(self.yellow_container_register)
                self.layoutWidget_9.setGeometry(QtCore.QRect(40, 140, 340, 33))
                self.layoutWidget_9.setObjectName("layoutWidget_9")
                self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget_9)
                self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_10.setObjectName("horizontalLayout_10")
                self.emailtitle_register = QtWidgets.QLabel(self.layoutWidget_9)
                self.emailtitle_register.setMinimumSize(QtCore.QSize(91, 21))
                self.emailtitle_register.setMaximumSize(QtCore.QSize(91, 21))
                font = QtGui.QFont()
                font.setFamily("Bahnschrift SemiBold Condensed")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.emailtitle_register.setFont(font)
                self.emailtitle_register.setAlignment(QtCore.Qt.AlignCenter)
                self.emailtitle_register.setObjectName("emailtitle_register")
                self.horizontalLayout_10.addWidget(self.emailtitle_register)
                self.email_lineedit_register = QtWidgets.QLineEdit(self.layoutWidget_9)
                self.email_lineedit_register.setMinimumSize(QtCore.QSize(241, 31))
                self.email_lineedit_register.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.email_lineedit_register.setObjectName("email_lineedit_register")
                self.horizontalLayout_10.addWidget(self.email_lineedit_register)
                self.verticalLayout_2.addWidget(self.yellow_container_register)
                self.loginregister_widget.addWidget(self.register_page)
                loginregister_mainwindow.setCentralWidget(self.centralwidget)

                self.register_button_login.clicked.connect(
                        lambda: navigation.switch_page(self.loginregister_widget, 1)
                )

                self.back_button_login.clicked.connect(self.close_application)
                self.back_button_register.clicked.connect(
                        lambda: navigation.switch_page(self.loginregister_widget, 0)
                )

                self.showpassword_button_login.clicked.connect(self.toggle_password_visibility)

                self.enter_button_login.clicked.connect(self.handle_login)
                self.enter_button_register.clicked.connect(self.handle_register)

                self.retranslateUi(loginregister_mainwindow)
                self.loginregister_widget.setCurrentIndex(0)
                QtCore.QMetaObject.connectSlotsByName(loginregister_mainwindow)

        def retranslateUi(self, loginregister_mainwindow):
                _translate = QtCore.QCoreApplication.translate
                loginregister_mainwindow.setWindowTitle(_translate("loginregister_mainwindow", "DJ Games Pass"))
                self.logintitle_login.setText(_translate("loginregister_mainwindow", "LOG IN"))
                self.back_button_login.setText(_translate("loginregister_mainwindow", "BACK"))
                self.enter_button_login.setText(_translate("loginregister_mainwindow", "ENTER"))
                self.register_button_login.setText(_translate("loginregister_mainwindow", "REGISTER"))
                self.usernametitle_login.setText(_translate("loginregister_mainwindow", "USERNAME:"))
                self.passwordtitle_login.setText(_translate("loginregister_mainwindow", "PASSWORD:"))
                self.showpassword_button_login.setText(_translate("loginregister_mainwindow", "Show Password"))
                self.regitertitle_register.setText(_translate("loginregister_mainwindow", "REGISTER"))
                self.back_button_register.setText(_translate("loginregister_mainwindow", "BACK"))
                self.enter_button_register.setText(_translate("loginregister_mainwindow", "ENTER"))
                self.usernametitle_register.setText(_translate("loginregister_mainwindow", "USERNAME:"))
                self.passwordtitle_register.setText(_translate("loginregister_mainwindow", "PASSWORD:"))
                self.firstnametitle_register.setText(_translate("loginregister_mainwindow", "FIRST NAME"))
                self.lastnametitle_register.setText(_translate("loginregister_mainwindow", "LAST NAME"))
                self.confirmpasswordtitle_register.setText(_translate("loginregister_mainwindow", "CONFIRM PASSWORD"))
                self.emailtitle_register.setText(_translate("loginregister_mainwindow", "EMAIL"))

        def toggle_password_visibility(self):
                # Toggle the echoMode of the password input field
                if self.password_lineedit_login.echoMode() == QLineEdit.Password:
                        self.password_lineedit_login.setEchoMode(QLineEdit.Normal)  # Show password
                else:
                        self.password_lineedit_login.setEchoMode(QLineEdit.Password)  # Hide password
        def handle_login(self):
                print("Login button clicked!")
                username = self.username_lineedit_login.text()
                password = self.password_lineedit_login.text()

                # Now call navigation.handle_login instead of handling it directly here
                navigation.handle_login(username, password, self)
        def handle_register(self):
                print("Register button clicked!")
                first_name = self.firstname_lineedit_register.text()
                last_name = self.lastname_lineedit_register.text()
                username = self.username_lineedit_register.text()
                email = self.email_lineedit_register.text()
                password = self.password_lineedit_register.text()

                # Call the register_user method in the navigation class
                navigation.register_user(first_name, last_name, username, email, password, self)

        def close_application(self):
                QtWidgets.QApplication.quit()

from resources import system_images

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loginregister_mainwindow = QtWidgets.QMainWindow()
    ui = Ui_loginregister_mainwindow()
    ui.setupUi(loginregister_mainwindow)
    loginregister_mainwindow.show()
    sys.exit(app.exec_())
