# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from utils.navigation import navigation

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1286, 745)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/default_images/icons/gamepass logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logoicon = QtWidgets.QLabel(self.centralwidget)
        self.logoicon.setGeometry(QtCore.QRect(380, 0, 491, 111))
        self.logoicon.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.logoicon.setText("")
        self.logoicon.setPixmap(QtGui.QPixmap(":/default_images/images/system__title.png"))
        self.logoicon.setScaledContents(True)
        self.logoicon.setObjectName("logoicon")
        self.threedoticon = QtWidgets.QPushButton(self.centralwidget)
        self.threedoticon.setGeometry(QtCore.QRect(1240, 40, 30, 30))
        self.threedoticon.setMinimumSize(QtCore.QSize(30, 30))
        self.threedoticon.setMaximumSize(QtCore.QSize(30, 30))
        self.threedoticon.setFocusPolicy(QtCore.Qt.NoFocus)
        self.threedoticon.setStyleSheet("border: none;")
        self.threedoticon.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/default_images/icons/three-dots-vertical_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.threedoticon.setIcon(icon1)
        self.threedoticon.setIconSize(QtCore.QSize(20, 20))
        self.threedoticon.setObjectName("threedoticon")
        self.username_label = QtWidgets.QLabel(self.centralwidget)
        self.username_label.setGeometry(QtCore.QRect(890, 40, 161, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_label.sizePolicy().hasHeightForWidth())
        self.username_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.username_label.setFont(font)
        self.username_label.setStyleSheet("QLabel {\n"
"                background-color: rgb(252, 183, 68);  /* Background color */\n"
"                color: grey;               /* Text color */\n"
"                border-radius: 15px;        /* Border radius */\n"
"                padding: 10px;              /* Padding */\n"
"                font-size: 12px;            /* Font size */\n"
"            }")
        self.username_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.username_label.setAlignment(QtCore.Qt.AlignCenter)
        self.username_label.setObjectName("username_label")
        self.search_bar = QtWidgets.QLineEdit(self.centralwidget)
        self.search_bar.setGeometry(QtCore.QRect(1060, 50, 160, 20))
        self.search_bar.setText("")
        self.search_bar.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.search_bar.setObjectName("search_bar")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(-1, 120, 1291, 623))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.layoutWidget)
        self.widget.setMinimumSize(QtCore.QSize(291, 621))
        self.widget.setMaximumSize(QtCore.QSize(291, 621))
        self.widget.setStyleSheet("background-color: rgb(252, 183, 68);\n"
"border-radius: 20px\n"
"")
        self.widget.setObjectName("widget")
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setGeometry(QtCore.QRect(80, 170, 133, 421))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.action_button = QtWidgets.QPushButton(self.widget1)
        self.action_button.setMinimumSize(QtCore.QSize(131, 41))
        self.action_button.setMaximumSize(QtCore.QSize(131, 41))
        self.action_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border- radius: 10px")
        self.action_button.setObjectName("action_button")
        self.verticalLayout.addWidget(self.action_button)
        self.roleplayinggame_button = QtWidgets.QPushButton(self.widget1)
        self.roleplayinggame_button.setMinimumSize(QtCore.QSize(131, 41))
        self.roleplayinggame_button.setMaximumSize(QtCore.QSize(131, 41))
        self.roleplayinggame_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border- radius: 10px")
        self.roleplayinggame_button.setObjectName("roleplayinggame_button")
        self.verticalLayout.addWidget(self.roleplayinggame_button)
        self.openworld_button = QtWidgets.QPushButton(self.widget1)
        self.openworld_button.setMinimumSize(QtCore.QSize(131, 41))
        self.openworld_button.setMaximumSize(QtCore.QSize(131, 41))
        self.openworld_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border- radius: 10px")
        self.openworld_button.setObjectName("openworld_button")
        self.verticalLayout.addWidget(self.openworld_button)
        self.scifi_button = QtWidgets.QPushButton(self.widget1)
        self.scifi_button.setMinimumSize(QtCore.QSize(131, 41))
        self.scifi_button.setMaximumSize(QtCore.QSize(131, 41))
        self.scifi_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border- radius: 10px")
        self.scifi_button.setObjectName("scifi_button")
        self.verticalLayout.addWidget(self.scifi_button)
        self.horror_button = QtWidgets.QPushButton(self.widget1)
        self.horror_button.setMinimumSize(QtCore.QSize(131, 41))
        self.horror_button.setMaximumSize(QtCore.QSize(131, 41))
        self.horror_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border- radius: 10px")
        self.horror_button.setObjectName("horror_button")
        self.verticalLayout.addWidget(self.horror_button)
        self.thirdperson_button = QtWidgets.QPushButton(self.widget1)
        self.thirdperson_button.setMinimumSize(QtCore.QSize(131, 41))
        self.thirdperson_button.setMaximumSize(QtCore.QSize(131, 41))
        self.thirdperson_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border- radius: 10px")
        self.thirdperson_button.setObjectName("thirdperson_button")
        self.verticalLayout.addWidget(self.thirdperson_button)
        self.adventure_button = QtWidgets.QPushButton(self.widget1)
        self.adventure_button.setMinimumSize(QtCore.QSize(131, 41))
        self.adventure_button.setMaximumSize(QtCore.QSize(131, 41))
        self.adventure_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border- radius: 10px")
        self.adventure_button.setObjectName("adventure_button")
        self.verticalLayout.addWidget(self.adventure_button)
        self.fantasy_button = QtWidgets.QPushButton(self.widget1)
        self.fantasy_button.setMinimumSize(QtCore.QSize(131, 41))
        self.fantasy_button.setMaximumSize(QtCore.QSize(131, 41))
        self.fantasy_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border- radius: 10px")
        self.fantasy_button.setObjectName("fantasy_button")
        self.verticalLayout.addWidget(self.fantasy_button)
        self.sandbox_button = QtWidgets.QPushButton(self.widget1)
        self.sandbox_button.setMinimumSize(QtCore.QSize(131, 41))
        self.sandbox_button.setMaximumSize(QtCore.QSize(131, 41))
        self.sandbox_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border- radius: 10px")
        self.sandbox_button.setObjectName("sandbox_button")
        self.verticalLayout.addWidget(self.sandbox_button)
        self.widget2 = QtWidgets.QWidget(self.widget)
        self.widget2.setGeometry(QtCore.QRect(50, 30, 183, 110))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.all_games_button = QtWidgets.QPushButton(self.widget2)
        self.all_games_button.setMinimumSize(QtCore.QSize(181, 51))
        self.all_games_button.setMaximumSize(QtCore.QSize(181, 51))
        self.all_games_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border- radius: 10px")
        self.all_games_button.setObjectName("all_games_button")
        self.verticalLayout_2.addWidget(self.all_games_button)
        self.featured_button = QtWidgets.QPushButton(self.widget2)
        self.featured_button.setMinimumSize(QtCore.QSize(181, 51))
        self.featured_button.setMaximumSize(QtCore.QSize(181, 51))
        self.featured_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border- radius: 10px")
        self.featured_button.setObjectName("featured_button")
        self.verticalLayout_2.addWidget(self.featured_button)
        self.horizontalLayout.addWidget(self.widget)
        self.stackwidget = QtWidgets.QStackedWidget(self.layoutWidget)
        self.stackwidget.setMinimumSize(QtCore.QSize(981, 611))
        self.stackwidget.setMaximumSize(QtCore.QSize(981, 611))
        self.stackwidget.setObjectName("stackwidget")
        self.all_games_page = QtWidgets.QWidget()
        self.all_games_page.setObjectName("all_games_page")
        self.allgames_center_label = QtWidgets.QLabel(self.all_games_page)
        self.allgames_center_label.setGeometry(QtCore.QRect(470, 280, 61, 41))
        self.allgames_center_label.setObjectName("allgames_center_label")
        self.stackwidget.addWidget(self.all_games_page)
        self.featured_page = QtWidgets.QWidget()
        self.featured_page.setObjectName("featured_page")
        self.featured_label = QtWidgets.QLabel(self.featured_page)
        self.featured_label.setGeometry(QtCore.QRect(470, 220, 61, 61))
        self.featured_label.setObjectName("featured_label")
        self.stackwidget.addWidget(self.featured_page)
        self.action_page = QtWidgets.QWidget()
        self.action_page.setObjectName("action_page")
        self.action_center_label = QtWidgets.QLabel(self.action_page)
        self.action_center_label.setGeometry(QtCore.QRect(470, 260, 61, 41))
        self.action_center_label.setObjectName("action_center_label")
        self.stackwidget.addWidget(self.action_page)
        self.rpg_page = QtWidgets.QWidget()
        self.rpg_page.setObjectName("rpg_page")
        self.roleplayinggame_center_label = QtWidgets.QLabel(self.rpg_page)
        self.roleplayinggame_center_label.setGeometry(QtCore.QRect(430, 200, 131, 41))
        self.roleplayinggame_center_label.setObjectName("roleplayinggame_center_label")
        self.stackwidget.addWidget(self.rpg_page)
        self.openworld_page = QtWidgets.QWidget()
        self.openworld_page.setObjectName("openworld_page")
        self.openworld_center_label = QtWidgets.QLabel(self.openworld_page)
        self.openworld_center_label.setGeometry(QtCore.QRect(490, 240, 101, 41))
        self.openworld_center_label.setObjectName("openworld_center_label")
        self.stackwidget.addWidget(self.openworld_page)
        self.scifi_page = QtWidgets.QWidget()
        self.scifi_page.setObjectName("scifi_page")
        self.scifi_center_label = QtWidgets.QLabel(self.scifi_page)
        self.scifi_center_label.setGeometry(QtCore.QRect(450, 200, 61, 41))
        self.scifi_center_label.setObjectName("scifi_center_label")
        self.stackwidget.addWidget(self.scifi_page)
        self.horror_page = QtWidgets.QWidget()
        self.horror_page.setObjectName("horror_page")
        self.horror_center_label = QtWidgets.QLabel(self.horror_page)
        self.horror_center_label.setGeometry(QtCore.QRect(400, 210, 61, 41))
        self.horror_center_label.setObjectName("horror_center_label")
        self.stackwidget.addWidget(self.horror_page)
        self.thridperson_page = QtWidgets.QWidget()
        self.thridperson_page.setObjectName("thridperson_page")
        self.thirdperson_center_label = QtWidgets.QLabel(self.thridperson_page)
        self.thirdperson_center_label.setGeometry(QtCore.QRect(440, 240, 141, 41))
        self.thirdperson_center_label.setObjectName("thirdperson_center_label")
        self.stackwidget.addWidget(self.thridperson_page)
        self.adventure_page = QtWidgets.QWidget()
        self.adventure_page.setObjectName("adventure_page")
        self.adventure_center_label = QtWidgets.QLabel(self.adventure_page)
        self.adventure_center_label.setGeometry(QtCore.QRect(490, 270, 61, 41))
        self.adventure_center_label.setObjectName("adventure_center_label")
        self.stackwidget.addWidget(self.adventure_page)
        self.fantasy_page = QtWidgets.QWidget()
        self.fantasy_page.setObjectName("fantasy_page")
        self.fantasy_center_label = QtWidgets.QLabel(self.fantasy_page)
        self.fantasy_center_label.setGeometry(QtCore.QRect(510, 240, 61, 41))
        self.fantasy_center_label.setObjectName("fantasy_center_label")
        self.stackwidget.addWidget(self.fantasy_page)
        self.sandbox_page = QtWidgets.QWidget()
        self.sandbox_page.setObjectName("sandbox_page")
        self.sandbox_center_label = QtWidgets.QLabel(self.sandbox_page)
        self.sandbox_center_label.setGeometry(QtCore.QRect(440, 290, 61, 41))
        self.sandbox_center_label.setObjectName("sandbox_center_label")
        self.stackwidget.addWidget(self.sandbox_page)
        self.horizontalLayout.addWidget(self.stackwidget)
        MainWindow.setCentralWidget(self.centralwidget)



        self.all_games_button.clicked.connect(
            lambda: navigation.switch_page(self.stackwidget, 0)  # Page index for "All Games"
        )
        # Connect other buttons to respective pages
        self.featured_button.clicked.connect(
            lambda: navigation.switch_page(self.stackwidget, 1)  # Page index for "Featured Games"
        )
        self.action_button.clicked.connect(
            lambda: navigation.switch_page(self.stackwidget, 2)  # Page index for "Action Games"
        )
        self.roleplayinggame_button.clicked.connect(
            lambda: navigation.switch_page(self.stackwidget, 3)  # Page index for "Roleplaying Games"
        )
        self.openworld_button.clicked.connect(
            lambda: navigation.switch_page(self.stackwidget, 4)  # Page index for "Open World Games"
        )
        self.scifi_button.clicked.connect(
            lambda: navigation.switch_page(self.stackwidget, 5)  # Page index for "Sci-Fi Games"
        )
        self.horror_button.clicked.connect(
            lambda: navigation.switch_page(self.stackwidget, 6)  # Page index for "Horror Games"
        )
        self.thirdperson_button.clicked.connect(
            lambda: navigation.switch_page(self.stackwidget, 7)  # Page index for "Third-Person Games"
        )
        self.adventure_button.clicked.connect(
            lambda: navigation.switch_page(self.stackwidget, 8)  # Page index for "Adventure Games"
        )
        self.fantasy_button.clicked.connect(
            lambda: navigation.switch_page(self.stackwidget, 9)  # Page index for "Fantasy Games"
        )
        self.sandbox_button.clicked.connect(
            lambda: navigation.switch_page(self.stackwidget, 10)  # Page index for "Sandbox Games"
        )

        self.retranslateUi(MainWindow)
        self.stackwidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Welcome to DJ Game Pass Homepage !"))
        self.username_label.setText(_translate("MainWindow", "placeholder_username"))
        self.search_bar.setPlaceholderText(_translate("MainWindow", "Search Here..."))
        self.action_button.setText(_translate("MainWindow", "ACTION"))
        self.roleplayinggame_button.setText(_translate("MainWindow", "ROLE PLAYING GAME"))
        self.openworld_button.setText(_translate("MainWindow", "OPEN WORLD"))
        self.scifi_button.setText(_translate("MainWindow", "SCI-FI"))
        self.horror_button.setText(_translate("MainWindow", "HORROR"))
        self.thirdperson_button.setText(_translate("MainWindow", "THIRD PERSON"))
        self.adventure_button.setText(_translate("MainWindow", "ADVENTURE"))
        self.fantasy_button.setText(_translate("MainWindow", "FANTASY"))
        self.sandbox_button.setText(_translate("MainWindow", "SANDBOX"))
        self.all_games_button.setText(_translate("MainWindow", "ALL GAMES"))
        self.featured_button.setText(_translate("MainWindow", "FEATURED"))
        self.allgames_center_label.setText(_translate("MainWindow", "ALL GAMES"))
        self.featured_label.setText(_translate("MainWindow", "FEATURED"))
        self.action_center_label.setText(_translate("MainWindow", "ACTION"))
        self.roleplayinggame_center_label.setText(_translate("MainWindow", "ROLE PLAYING GAME"))
        self.openworld_center_label.setText(_translate("MainWindow", "OPEN WORLD"))
        self.scifi_center_label.setText(_translate("MainWindow", "SCI-FI"))
        self.horror_center_label.setText(_translate("MainWindow", "HORROR"))
        self.thirdperson_center_label.setText(_translate("MainWindow", "THIRD PERSON"))
        self.adventure_center_label.setText(_translate("MainWindow", "ADVENTURE"))
        self.fantasy_center_label.setText(_translate("MainWindow", "FANTASY"))
        self.sandbox_center_label.setText(_translate("MainWindow", "SANDBOX"))

from resources import system_images

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

