# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(963, 576)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/system_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.settingsicon = QtWidgets.QLabel(self.centralwidget)
        self.settingsicon.setGeometry(QtCore.QRect(20, 10, 21, 21))
        self.settingsicon.setStyleSheet("\n"
"border-image: url(:/dashboard_icons/Downloads/588a6507d06f6719692a2d15.png);")
        self.settingsicon.setText("")
        self.settingsicon.setObjectName("settingsicon")
        self.logoicon = QtWidgets.QLabel(self.centralwidget)
        self.logoicon.setGeometry(QtCore.QRect(60, 0, 41, 41))
        self.logoicon.setStyleSheet("border-image: url(:/default_images/icons/gamepass logo.png)")
        self.logoicon.setText("")
        self.logoicon.setObjectName("logoicon")
        self.LogoFont = QtWidgets.QLabel(self.centralwidget)
        self.LogoFont.setGeometry(QtCore.QRect(100, 5, 201, 31))
        self.LogoFont.setStyleSheet("font: 17pt \"Bahnschrift SemiLight Condensed\";\n"
"")
        self.LogoFont.setObjectName("LogoFont")
        self.upperusername = QtWidgets.QLabel(self.centralwidget)
        self.upperusername.setGeometry(QtCore.QRect(800, 10, 101, 21))
        self.upperusername.setStyleSheet("border-image: url(:/user_dash icons/yellow bg.jpg);\n"
"font: 10pt \"Bahnschrift SemiLight Condensed\";\n"
"border-radius: 10px;\n"
"\n"
"")
        self.upperusername.setAlignment(QtCore.Qt.AlignCenter)
        self.upperusername.setObjectName("upperusername")
        self.dotssettingicon = QtWidgets.QLabel(self.centralwidget)
        self.dotssettingicon.setGeometry(QtCore.QRect(910, 10, 31, 21))
        self.dotssettingicon.setStyleSheet("\n"
"border-image: url(:/default_images/icons/three-dots-vertical_1.png)")
        self.dotssettingicon.setText("")
        self.dotssettingicon.setObjectName("dotssettingicon")
        self.yellow_container_account = QtWidgets.QWidget(self.centralwidget)
        self.yellow_container_account.setGeometry(QtCore.QRect(0, 40, 971, 31))
        self.yellow_container_account.setStyleSheet("background-color: rgb(253, 183, 69);")
        self.yellow_container_account.setObjectName("yellow_container_account")
        self.accounttitle_account = QtWidgets.QLabel(self.yellow_container_account)
        self.accounttitle_account.setGeometry(QtCore.QRect(310, 7, 111, 16))
        self.accounttitle_account.setStyleSheet("font: 75 14pt \"Berlin Sans FB Demi\";\n"
"label.setGraphicsEffect(shadow)\n"
"shadow.setBlurRadius(15)")
        self.accounttitle_account.setObjectName("accounttitle_account")
        self.myaccountbutton = QtWidgets.QPushButton(self.centralwidget)
        self.myaccountbutton.setGeometry(QtCore.QRect(18, 190, 101, 23))
        self.myaccountbutton.setStyleSheet("background:transparent ;\n"
"border: none;\n"
"font: 15pt \"Bahnschrift SemiLight Condensed\";")
        self.myaccountbutton.setObjectName("myaccountbutton")
        self.downloadedgamesbutton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadedgamesbutton.setGeometry(QtCore.QRect(16, 220, 151, 23))
        self.downloadedgamesbutton.setStyleSheet("background:transparent ;\n"
"border: none;\n"
"font: 14pt \"Bahnschrift SemiLight Condensed\";")
        self.downloadedgamesbutton.setObjectName("downloadedgamesbutton")
        self.account_container_widget = QtWidgets.QStackedWidget(self.centralwidget)
        self.account_container_widget.setGeometry(QtCore.QRect(230, 80, 721, 481))
        self.account_container_widget.setObjectName("account_container_widget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.white_accountcontainer_mainwidget = QtWidgets.QWidget(self.page)
        self.white_accountcontainer_mainwidget.setGeometry(QtCore.QRect(150, 0, 401, 451))
        self.white_accountcontainer_mainwidget.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.white_accountcontainer_mainwidget.setObjectName("white_accountcontainer_mainwidget")
        self.mainusericon = QtWidgets.QLabel(self.white_accountcontainer_mainwidget)
        self.mainusericon.setGeometry(QtCore.QRect(40, 30, 101, 101))
        self.mainusericon.setStyleSheet("\n"
"border-image: url(:/dashboard_icons/icons/user.png);")
        self.mainusericon.setText("")
        self.mainusericon.setObjectName("mainusericon")
        self.mainusername = QtWidgets.QLabel(self.white_accountcontainer_mainwidget)
        self.mainusername.setGeometry(QtCore.QRect(140, 100, 291, 21))
        self.mainusername.setStyleSheet("font: 13pt \"Bahnschrift SemiLight Condensed\";\n"
"\n"
"\n"
"")
        self.mainusername.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mainusername.setObjectName("mainusername")
        self.discordicon = QtWidgets.QLabel(self.white_accountcontainer_mainwidget)
        self.discordicon.setGeometry(QtCore.QRect(60, 190, 25, 25))
        self.discordicon.setStyleSheet("border-image: url(:/dashboard_icons/Downloads/discord-removebg-preview.png);")
        self.discordicon.setText("")
        self.discordicon.setObjectName("discordicon")
        self.twitchicon = QtWidgets.QLabel(self.white_accountcontainer_mainwidget)
        self.twitchicon.setGeometry(QtCore.QRect(95, 192, 20, 20))
        self.twitchicon.setStyleSheet("border-image: url(:/dashboard_icons/Downloads/twitch-removebg-preview.png);")
        self.twitchicon.setText("")
        self.twitchicon.setObjectName("twitchicon")
        self.email_label = QtWidgets.QLabel(self.white_accountcontainer_mainwidget)
        self.email_label.setGeometry(QtCore.QRect(30, 150, 41, 21))
        self.email_label.setStyleSheet("font: 13pt \"Bahnschrift SemiLight Condensed\";\n"
"rgb:(86, 86, 86)")
        self.email_label.setObjectName("email_label")
        self.Password_label = QtWidgets.QLabel(self.white_accountcontainer_mainwidget)
        self.Password_label.setGeometry(QtCore.QRect(30, 180, 61, 21))
        self.Password_label.setStyleSheet("font: 13pt \"Bahnschrift SemiLight Condensed\";\n"
"rgb:(86, 86, 86)")
        self.Password_label.setObjectName("Password_label")
        self.editemailpassbutton = QtWidgets.QPushButton(self.white_accountcontainer_mainwidget)
        self.editemailpassbutton.setGeometry(QtCore.QRect(110, 340, 181, 31))
        self.editemailpassbutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.editemailpassbutton.setStyleSheet("font: 11pt \"Bahnschrift SemiLight Condensed\";\n"
"background-color: rgb(253, 183, 69);\n"
"border-radius: 15px;")
        self.editemailpassbutton.setCheckable(False)
        self.editemailpassbutton.setFlat(False)
        self.editemailpassbutton.setObjectName("editemailpassbutton")
        self.email_display = QtWidgets.QLabel(self.white_accountcontainer_mainwidget)
        self.email_display.setGeometry(QtCore.QRect(70, 150, 311, 21))
        self.email_display.setStyleSheet("font: 13pt \"Bahnschrift SemiLight Condensed\";\n"
"rgb:(86, 86, 86)")
        self.email_display.setObjectName("email_display")
        self.Password_display = QtWidgets.QLabel(self.white_accountcontainer_mainwidget)
        self.Password_display.setGeometry(QtCore.QRect(100, 180, 281, 21))
        self.Password_display.setStyleSheet("font: 13pt \"Bahnschrift SemiLight Condensed\";\n"
"rgb:(86, 86, 86)")
        self.Password_display.setObjectName("Password_display")
        self.email_pass_confirmpass_widget = QtWidgets.QWidget(self.white_accountcontainer_mainwidget)
        self.email_pass_confirmpass_widget.setGeometry(QtCore.QRect(50, 210, 321, 111))
        self.email_pass_confirmpass_widget.setObjectName("email_pass_confirmpass_widget")
        self.email_label_2 = QtWidgets.QLabel(self.email_pass_confirmpass_widget)
        self.email_label_2.setGeometry(QtCore.QRect(10, 10, 41, 21))
        self.email_label_2.setStyleSheet("font: 13pt \"Bahnschrift SemiLight Condensed\";\n"
"rgb:(86, 86, 86)")
        self.email_label_2.setObjectName("email_label_2")
        self.Password_label_2 = QtWidgets.QLabel(self.email_pass_confirmpass_widget)
        self.Password_label_2.setGeometry(QtCore.QRect(10, 40, 61, 21))
        self.Password_label_2.setStyleSheet("font: 13pt \"Bahnschrift SemiLight Condensed\";\n"
"rgb:(86, 86, 86)")
        self.Password_label_2.setObjectName("Password_label_2")
        self.Password_label_3 = QtWidgets.QLabel(self.email_pass_confirmpass_widget)
        self.Password_label_3.setGeometry(QtCore.QRect(10, 70, 101, 21))
        self.Password_label_3.setStyleSheet("font: 13pt \"Bahnschrift SemiLight Condensed\";\n"
"rgb:(86, 86, 86)")
        self.Password_label_3.setObjectName("Password_label_3")
        self.email_lineedit = QtWidgets.QLineEdit(self.email_pass_confirmpass_widget)
        self.email_lineedit.setGeometry(QtCore.QRect(70, 10, 231, 20))
        self.email_lineedit.setObjectName("email_lineedit")
        self.password_lineedit = QtWidgets.QLineEdit(self.email_pass_confirmpass_widget)
        self.password_lineedit.setGeometry(QtCore.QRect(70, 40, 231, 20))
        self.password_lineedit.setObjectName("password_lineedit")
        self.confirmpassword_lineedit = QtWidgets.QLineEdit(self.email_pass_confirmpass_widget)
        self.confirmpassword_lineedit.setGeometry(QtCore.QRect(120, 70, 181, 20))
        self.confirmpassword_lineedit.setObjectName("confirmpassword_lineedit")
        self.account_container_widget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.downloadedgamesbutton_2 = QtWidgets.QPushButton(self.page_2)
        self.downloadedgamesbutton_2.setGeometry(QtCore.QRect(290, 220, 151, 23))
        self.downloadedgamesbutton_2.setStyleSheet("background:transparent ;\n"
"border: none;\n"
"font: 14pt \"Bahnschrift SemiLight Condensed\";")
        self.downloadedgamesbutton_2.setObjectName("downloadedgamesbutton_2")
        self.account_container_widget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.account_container_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DJ Game Pass USER"))
        self.LogoFont.setText(_translate("MainWindow", "DonnelJan Game Pass"))
        self.upperusername.setText(_translate("MainWindow", "GHANZTAH_KOZAH"))
        self.accounttitle_account.setText(_translate("MainWindow", "ACCOUNT"))
        self.myaccountbutton.setText(_translate("MainWindow", "My Account"))
        self.downloadedgamesbutton.setText(_translate("MainWindow", "Downloaded Games"))
        self.mainusername.setText(_translate("MainWindow", "placeholder_username"))
        self.email_label.setText(_translate("MainWindow", "Email:"))
        self.Password_label.setText(_translate("MainWindow", "Password:"))
        self.editemailpassbutton.setText(_translate("MainWindow", "EDIT PROFILE"))
        self.email_display.setText(_translate("MainWindow", "placeholder@email"))
        self.Password_display.setText(_translate("MainWindow", "placeholder_password"))
        self.email_label_2.setText(_translate("MainWindow", "Email:"))
        self.Password_label_2.setText(_translate("MainWindow", "Password:"))
        self.Password_label_3.setText(_translate("MainWindow", "Confirm Password:"))
        self.downloadedgamesbutton_2.setText(_translate("MainWindow", "Downloaded Games"))

from resources import system_images


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
